base: "http://www.sczg.unizg.hr"
urls:
    index:       "/student-servis/ponuda-poslova/"
    marketing:   "/student-servis/vijest/2015-04-14-poslovi-promidzbe/"
    ducani:      "/student-servis/vijest/2015-04-14-poslovi-u-trgovini/"
    ugostitelji: "/student-servis/vijest/2015-04-14-poslovi-u-ugostiteljstvu/"
    ciscenje:    "/student-servis/vijest/2015-04-14-poslovi-ciscenja/"
    proizvodnja: "/student-servis/vijest/2015-04-14-poslovi-u-proizvodnji/"
    turizam:     "/student-servis/vijest/2015-04-14-poslovi-u-turizmu/"
    fizicki:     "/student-servis/vijest/2015-04-14-fizicki-poslovi/"
    razno:       "/student-servis/vijest/2015-04-14-razni-poslovi/"
    admin:       "/student-servis/vijest/2015-04-14-poslovi-u-administraciji/"
    skladiste:   "/student-servis/vijest/2015-04-14-rad-u-skladistima/"
agent: "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:62.0) Gecko/20100101 Firefox/62.0"
interval: 21600 # 6 hrs
timeout: 20
port: ":8080"
archive: 14 # archive ads older than 14 days, ALSO rm from active ads 