base: "http://localhost:8888"
urls:
  index:       "/index"
  razno:       "/razno"
  admin:       "/admin"
  skladiste:   "/skladiste"
  ducani:      "/prodaja"
  marketing:   "/promo"
  ugostitelji: "/ugostitelji"
  ciscenje:    "/ciscenje"
  proizvodnja: "/proizvodnja"
  fizicki:     "/fizicki"
  turizam:     "/turizam"
agent: "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:62.0) Gecko/20100101 Firefox/62.0"
interval: 120 # 21600 # 6 hrs
timeout: 10
port: ":8080"
archive: 14 # archive ads older than 14 days, ALSO rm from active ads  